version: "3"
services:
  ganache:
    image: paras/eth-ganache:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    image: paras/eth-server:1.0.0
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - ganache

  next:
    image: paras/eth-next:1.0.0
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - dapp
